### ISSUE TITLE
[FEATURE] read a task config

### ISSUE THREAD

**Issue by yuchiki** [yuchiki/atcoderHelper#45]
# Type of change

- [x] Other

# Description

add a function to read below:

```yaml
contestID: "foo"
taskID: "bar"
template: "default"
```
