### ISSUE TITLE
[FEATURE] save test result

### ISSUE THREAD

**Issue by yuchiki** [yuchiki/atcoderHelper#50]
# Type of change

- [x] Add a new feature to an existing command

# Description

## Command

- ach test

## The New Behaviour

- save status

status.yaml
```yaml
test:
  status: all ok  | n/m passed. 
  cases:
    - name: "1"
      status: "passed"
    - name: "2"
      status: "failed"
      description: "expected 4, but actual 5"  
```
